name: CI Workflow

on:
  push:
    paths:
      - "packages/**/*"
      - "scripts/**/*"
      - "bun.lockdb"
      - ".github/workflows/*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Lint
        run: bun lint

      - name: Test
        run: bun test
